// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQk-JqBgqCj4HktpB54Hk9mjLnnXVUy4',
    appId: '1:34963714637:web:b532928b95e38f78de2204',
    messagingSenderId: '34963714637',
    projectId: 'contactapp-578cb',
    authDomain: 'contactapp-578cb.firebaseapp.com',
    storageBucket: 'contactapp-578cb.appspot.com',
    measurementId: 'G-BR812HZJEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmTX0zdB1wwzoq7LlJHuexzZUe2iH5zYI',
    appId: '1:34963714637:android:6f0f526c1af2398dde2204',
    messagingSenderId: '34963714637',
    projectId: 'contactapp-578cb',
    storageBucket: 'contactapp-578cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oHT9dpDnIf0NmGbf-LI7aafllPOozQo',
    appId: '1:34963714637:ios:a24a015eb812faecde2204',
    messagingSenderId: '34963714637',
    projectId: 'contactapp-578cb',
    storageBucket: 'contactapp-578cb.appspot.com',
    iosClientId: '34963714637-c0i5ejcqofe8nfjlourc0nhjcg067v5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_oHT9dpDnIf0NmGbf-LI7aafllPOozQo',
    appId: '1:34963714637:ios:a24a015eb812faecde2204',
    messagingSenderId: '34963714637',
    projectId: 'contactapp-578cb',
    storageBucket: 'contactapp-578cb.appspot.com',
    iosClientId: '34963714637-c0i5ejcqofe8nfjlourc0nhjcg067v5o.apps.googleusercontent.com',
    iosBundleId: 'com.example.contactapp',
  );
}
